### ISSUE TITLE
OWL files not as expected

### ISSUE THREAD

**Issue by hrshdhgd** [microbiomedata/metadata_converter#5]
This is what the owl files for all 'target' besides 'emp' and 'mixs' read:

`YO SLOT: {}
YO SLOT: {}
YO SLOT: {}
YO SLOT: {}
YO SLOT: {}
YO SLOT: {}
YO SLOT: {}
YO SLOT: {'biolinkml': 'https://w3id.org/biolink/biolinkml/', 'mixs.vocab': 'https://w3id.org/mixs/vocab/', 'MIXS': 'https://w3id.org/mixs/terms/'}
YO SLOT: {}
YO SLOT: {}
YO SLOT: {}
YO SLOT: {'core field': {'description': 'basic fields'}, 'environment field': {'description': 'field describing environmental aspect of a sample'}, 'investigation field': {'description': 'field describing aspect of the investigation/study to which the sample belongs'}, 'nucleic acid sequence source field': {}, 'sequencing field': {}, 'mixs extension field': {}, 'submitted_to_insdc': {'is_a': 'investigation field', 'aliases': ['submitted to insdc'], 'description': 'Depending on the study (large-scale e.g. done with next generation sequencing technology, or small-scale) sequences have to be submitted to SRA (Sequence Read Archive), DRA (DDBJ Read Archive) or via the classical Webin/Sequin systems to Genbank, ENA and DDBJ. Although this field is mandatory, it is meant as a self-test field, therefore it is not necessary to include this field in contextual data submitted to databases', 'pattern': '{boolean}', 'examples': [{'value': 'yes'}], 'comments': ['Expected value: boolean', 'Preferred unit: ', 'Position: 1.0']}, 'investigation_type': {'is_a': 'investigation field', 'aliases': ['investigation type'], 'description': 'Nucleic Acid Sequence Report is the root element of all MIGS/MIMS compliant reports as standardized by Genomic Standards Consortium. This field is either eukaryote,bacteria,virus,plasmid,organelle, metagenome,mimarks-survey, mimarks-specimen, metatranscriptome, single amplified genome, metagenome-assembled genome, or uncultivated viral genome', 'pattern': '[eukaryote|bacteria_archaea|plasmid|virus|organelle|metagenome|metatranscriptome|mimarks-survey|mimarks-specimen|misag|mimag|miuvig]', 'examples': [{'value': 'metagenome'}], 'comments': ['Expected value: eukaryote, bacteria_archaea, plasmid, virus, organelle, metagenome,mimarks-survey, mimarks-specimen, metatranscriptome, single amplified genome, metagenome-assembled genome, or uncultivated viral genomes', 'Preferred unit: ', 'Position: 2.0']}, 'sample_name': {'is_a': 'core field', 'aliases': ['sample name '], 'description': 'Sample Name is a name that you choose for the sample. It can have any format, but we suggest that you make it concise, unique and consistent within your lab, and as informative as possible. Every Sample Name from a single Submitter must be unique. ', 'pattern': '', 'examples': [{'value': ''}], 'comments': ['Expected value: ', 'Preferred unit: ', 'Position: ']}, 'project_name': {'is_a': 'investigation field', 'aliases': ['project name'],`

Due to this bug, the OLS only deploys 'emp' and 'miss' only. (2/7 ontologies)

**Comment by cmungall** [comment]
Oh dear I was using my dev copy of linkml with debugging prints, bad me.
Can you try and refresh via makefile?

**Comment by hrshdhgd** [comment]
Re-running the make file solved the issue.
